groups:
  - name: app_alerts
    rules:
      - alert: AppDown
        expr: up{job="app-server"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Aplikasi Down!"
          description: "Target {{ $labels.instance }} tidak merespons scrape Prometheus."

      - alert: HighErrorRate
        expr: ((sum(rate(http_requests_total{status=~"5.."}[2m])) or vector(0)) / sum(rate(http_requests_total[2m]))) * 100 > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High 5xx Error Rate Detected"
          description: "Error rate mencapai {{ $value | printf \"%.2f\" }}%."

      - alert: HighLatencyP95
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Latency p95 (> 1s)"
          description: "Latency p95 saat ini: {{ $value | printf \"%.2f\" }}s."