services:
  db:
    container_name: db-server
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .env:/app/.env
  app:
    container_name: app-server
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - .env
    ports:
      - "80:${APP_PORT}"
    depends_on:
      - db
  prometheus:
    container_name: prometheus-server
    image: prom/prometheus:v3.13.2
    ports:
      - "9090:9090"
    volumes:
      - ./../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
  grafana:
    container_name: grafana-server
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  postgres_data:
  grafana_data:
