---
- hosts: servers
  become: "{{ ansible_become | default(true) }}"
  tasks:
    - name: Remove existing application directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: absent
    - name: Create application directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'
    - name: Deploy file
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ app_dir }}/"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'
      loop:
        - "{{ './../../docker' }}"
        - "{{ './../../app' }}"
        - "{{ './../../prometheus' }}"
        - "{{ './../../grafana' }}"
    - name: Build image Docker Compose
      ansible.builtin.command:
        cmd: docker compose -f docker/compose.yaml build
        chdir: "{{ app_dir }}"
    - name: Start containers Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}/docker"
        state: present
        env_files:
          - ".env"
        recreate: 'always'
        files:
          - compose.yaml
